### ISSUE TITLE
Parsing problems

### ISSUE THREAD

**Issue by devragj** [CLSPhila/RecordLib#18]
There's a typo in the pattern open_sequence.  There should be a * after (sequence_continued new_line), not a ?.
open_sequence = ws* sequence_num ws+ statute ws+ (grade ws+)? description (ws+ sequence_disposition)? new_line (sequence_continued new_line)* open_sequence_header?

In several documents, I found closed cases with no dispositions.  See CP-28-MD-0000229-2017.
(Also CP-54-CR-0001986-2009, CP-45-CR-0001253-2010.)

An exclamation mark can occur in descriptions.  See CP-20-MD-0000282-2008.  So far I've just seen this when the statute is 0 (see below), and they tell you to call the "Help Desk!".

Unfortunately, a continued sequence can start with a number.  See for example CP-62-CR-0000368-2013, line 11, "13 Years Old".  So this pattern doesn't always work:
sequence_continued = ws+ !(number ws) !date words ws* words?
(Also in CP-32-CR-0000383-2008.  Also when the statute is 0, as in CP-20-MD-0000282-2008.)

In several documents, I found a statute starting with "LO".  See CP-25-CR-0000099-2018, line 86, also CP-67-MD-0001728-2014, CP-39-MD-0001759-2014.  Also, in CP-51-CR-0000002-2015, there's a statute which starts with "CO".

In several documents, I found a backslash (\) in a sequence.  See CP-01-MD-0000932-2017, line 39.
"Fail To Not Police Of Acc\ Damage To"
You might want to add \\ to content_char_no_ws.  (Also in CP-15-MD-0001744-2017, CP-06-MD-0000302-2018, and two more.  The same phrase occurs, and also "Fail To Not Police Of Accident\ Injury")

In CP-22-CR-0001282-2007, line 5, there is an alias in quotes.

I found five unusual patterns.  (But, I have found three of them occurring twice.)
In CP-15-MD-0000793-2008, there is an unusual Arrest Dt. line which in fact takes two lines:
Arrest Dt: 05/15/2004         Trial Dt:                    Legacy No:    137110
                                                                2744CR2004
(Also in CP-36-CR-0000258-2015.)

In CP-51-MD-0000950-2008, line 108, the Arrest Dt line has a fourth item:
Arrest Dt: 01/12/2007   Disp Date: 07/02/2007    Disp Judge: Merriweather, Ronald B.   MC Appeal

In CP-45-MD-0000058-2008, line 13, the line after "Next Action" starts with "Prob #:".
Prob #: 90044-TSF-2007         PSI#:
(Also in CP-03-CR-0000809-2011, CP-65-CR-0000546-2007, CP-52-CR-0000115-2013.)

The statute is all zeros, in CP-54-MD-0000532-2013 line 129.  Sometimes, when that happens, the Grade and Description are blank.
2       0 § 0 §§ 0
Also in CP-04-MD-0000200-2007.

In CP-49-MD-0000509-2009, line 3, Proc Status has no value:
CP-41-MD-0000086-2008           Proc Status:            DC No:          OTN:
(Also in CP-28-MD-0000194-2012, line 3.  Also in CP-44-MD-0000055-2017, line 14.)

Here is a parsing problem. In CP-23-CR-0001296-2010, line 36, there is a word which is just an &.  The line is:
3 	75 § 3731 §§ A3* 	M2 	Dr Und The Inf Of Alco & Cont Subs 	Migrated Disposition
Somewhere in the parsing, the & is lost.  It's not present in slines.
This results in two spaces in a row, like this (in between Alco and Cont):
Dr Und The Inf Of Alco  Cont Subs
That section then doesn't parse as words.
(Also in CP-54-CR-0001737-2008.)

In CP-63-MD-0000344-2009, at the beginning, there is an extra blank line instead of "Active" or "Closed".
Also in CP-21-MD-0000552-2018, CP-22-MD-0000083-2015.
In CP-14-MD-0000606-2007, at the end of page 1.  The document doesn't parse as a summary.  I don't know why.

In CP-21-CR-0000711-2008, the last page just has two continuation lines, and then some blank lines.
The document doesn't parse as a summary.  Maybe this is the problem.

**Comment by NateV** [comment]
Super helpful. Thanks! I'll download these and make some fixes.

That "Call Help Desk!" thing is funny. 

I also found a summary that was just 185 pages of empty case records. The defendant was listed as the Mongomery County District Attorney's office.

What an odd system this is.

**Comment by devragj** [comment]
It's pretty fascinating, what can go wrong.  Right now, if I download new documents, I'm mostly getting the issues listed above.  Once most of these are fixed, I can download more files and see what else can happen.

**Comment by devragj** [comment]
Great that you've done all this.  Now that you've made so many changes, I'm going through to see what's left.  Turns out, there was one problem which I didn't understand on the first go round.  It's in the document CP-61-MD-0000015-2008, at the end of page 1.  It looks like the Program Period was really long, namely, "1 year less 1 day to 2 years less 1 day".  So then the Sentence Length is "Min: 11 Month(s) 29 Day(s) Max: 1 Year(s) 11 Month(s) 29 Day(s)"  Naturally this doesn't fit well on one line.  In the .pdf the two seem to be on one line, overlapping each other, but then pdftotext splits them up, awkwardly, into two lines, like so:
10/06/2017        Confinement            1 year less 1 day to 2 years less 1 Min:
                                                            day 11 Month(s) 29 Day(s) Max: 1 Year(s) 11 Month(s) 29 Day(s)

**Comment by NateV** [comment]
pr #27
