### ISSUE TITLE
MDJ Parsing Issue

### ISSUE THREAD

**Issue by devragj** [CLSPhila/RecordLib#22]
There is an issue with `arrest_disp`.
```
arrest_disp = ws* arrest_date (ws+ proc_stat_cont)? ws* disp_date
arrest_date = "Arrest Date:" ws* date?
```

Note, `arrest_date` has `ws* date?`
If "Arrest Date:" is present but the date itself is missing, then `arrest_date` will eat all the white space, and then the `ws+` in `arrest_disp` won't match.  See for example MJ-12101-CR-0000152-2014.

The same issue occurs in the `bail_info` line:
```
bail_info = ws* bail_type ws+ bail_amount ws+ bail_status
bail_type = "Bail Type:" ws* words?
bail_amount = "Bail Amount:" ws* words?
bail_status = "Bail Status:" ws* words?
```

For example, in MJ-31101-CR-0000722-2011, the text "Bail Type:" is present, but there is no Bail Type given.
So then `bail_type` matches all the white space, and the `ws+` before `bail_amount` doesn't match.

**Comment by NateV** [comment]
erp.  MJ-12101-CR-0000152-2014 reveals another issue too. 

I thought the structure of the summary body had to be like

[county]
[case statuses for cases in that county]
    [cases]

But this summary sheet also has this "Statewide" token, which nests more deeply:

Statewide
[status]
  [county]
  [cases]

**Comment by NateV** [comment]
and in MJ-31101-CR-0000722-2011, the first instance i've seen of a MD summary having a sentence, so need to add that to the grammar.
