### ISSUE TITLE
Another MDJ Parsing Issue

### ISSUE THREAD

**Issue by devragj** [CLSPhila/RecordLib#24]
There can be a section of cases which starts with the line "Statewide".
After that, the next  line will have the type of case, for example, "Closed".
After that, there will be a breakdown into counties.

See for example MJ-15101-CR-0000073-2017, where there are two counties under "Closed".  
The document MJ-50101-CR-0000203-2016 has two types of cases under "Statewide", namely "Closed" and "Inactive".

Here is one more issue:
in MJ-14101-CR-0000506-2017, there is a new section at the end of the case, called "Program Type".

**Comment by NateV** [comment]
pr #27
