### ISSUE TITLE
More MDJ issues, mostly overflow

### ISSUE THREAD

**Issue by devragj** [CLSPhila/RecordLib#28]
Sometimes a case ends near the bottom of a page, so that the "County" and "Closed" lines occur at the end of the page, and then are repeated on the next page.  See MJ-47101-CR-0000247-2012, pages 2 to 3.

Alternatively, there can be just a "Closed" line at the end of a page, and then "County" and "Closed" at the beginning of the next page.  See MJ-14101-CR-0000538-2018, pages 3 to 4.

In MJ-52101-CR-0000034-2012, the "County" and "Inactive" lines are repeated at the top of page 2, but then there are no more cases in that category.

MJ-15101-CR-0000073-2017 is similar to the second case above, but within a Statewide section.

In general, a case ends in a blank line and then a horizontal rule.  Sometimes a case is almost complete at the end of a page, but one or both of these ending lines are on the next page.
See MJ-36101-CR-0000016-2012, pages 5 to 6 (one ending line on the new page) and MJ-12101-CR-0000152-2014, pages 1 to 2 (both ending lines on the new page).
MJ-15101-CR-0000081-2016, pages 2 to 3, has one ending line on the new page, and, in addition, switches to a new group after that.

I don't know what is wrong in MJ-10101-CR-0000380-2017 or MJ-53101-CR-0000550-2014.  Once the above issues are fixed, I could look at them again.

In MJ-38101-CR-0000243-2007, the aliases take two lines.

**Comment by NateV** [comment]
would be resolved by #27

**Comment by NateV** [comment]
pr #27
